# Generated by Django 4.0.4 on 2022-06-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Contacto')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos de Contacto')),
                ('email', models.EmailField(max_length=50, verbose_name='Email de Contacto')),
                ('direccion', models.CharField(max_length=60, verbose_name='dirección de Contacto')),
                ('telefono', models.CharField(max_length=9, verbose_name='teléfono de Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Fundacion')),
                ('descripcion', models.CharField(max_length=800, verbose_name='Descripcion de la Fundacion')),
                ('imagen', models.ImageField(upload_to='fundaciones/', verbose_name='Imágen de la Fundacion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('color', models.CharField(max_length=50, verbose_name='Color de Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('tipo', models.IntegerField(choices=[[0, 'bandana'], [1, 'correa'], [2, 'identificacion']])),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imágen del Producto')),
            ],
        ),
    ]
