# Generated by Django 4.0.4 on 2022-07-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
