# Generated by Django 4.0.5 on 2022-06-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idContacto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Contacto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Contacto')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos de Contacto')),
                ('direccion', models.CharField(max_length=60, verbose_name='dirección de Contacto')),
                ('telefono', models.CharField(max_length=9, verbose_name='teléfono de Contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Producto')),
                ('color', models.CharField(max_length=50, verbose_name='Color de Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('tipo', models.CharField(max_length=60, verbose_name='Tipo del Producto')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imágen del Producto')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
