# Generated by Django 4.0.4 on 2022-07-04 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fundacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundacion',
            name='imagen',
        ),
    ]
