# Generated by Django 4.0.4 on 2022-07-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_fundacion_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundacion',
            name='imagen',
            field=models.ImageField(default=1, upload_to='fundaciones/', verbose_name='Imágen de la Fundacion'),
            preserve_default=False,
        ),
    ]
