# Generated by Django 4.0.5 on 2022-06-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_producto_idproducto_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.IntegerField(choices=[[0, 'bandana'], [1, 'correa'], [2, 'identificacion']]),
        ),
    ]
