# Generated by Django 4.0.5 on 2022-06-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Fundacion')),
                ('descripcion', models.CharField(max_length=800, verbose_name='Descripcion de la Fundacion')),
                ('imagen', models.ImageField(upload_to='imagenes/', verbose_name='Imágen de la Fundacion')),
            ],
        ),
    ]
