# Generated by Django 4.0.5 on 2022-06-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fundacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='imagen',
            field=models.ImageField(upload_to='fundaciones/', verbose_name='Imágen de la Fundacion'),
        ),
    ]
