# Generated by Django 4.0.5 on 2022-06-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_fundacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='idContacto',
        ),
        migrations.AddField(
            model_name='contacto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
