# Generated by Django 4.0.5 on 2022-06-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contacto_idcontacto_contacto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='email',
            field=models.EmailField(default=1, max_length=50, verbose_name='Email de Contacto'),
            preserve_default=False,
        ),
    ]
